baseURL = 'https://example.org/'
languageCode = 'en-us'

theme = "paper"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'dillondesilva'                 # github.com/YOUR_GITHUB_ID
  instagram = 'dillondesilvaaa'           # instagram.com/YOUR_INSTAGRAM_ID

  # home page profile
  avatar = 'https://gravatar.com/userimage/59791647/890daabe4f340a6f211b72acf199b8ae.jpeg?size=256'                 # gravatar email or image url
  name = 'Dillon de Silva'
  bio = 'My little microblog filled with lots of random, possibly useful notes'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon